services:
  api:
    build: .
    container_name: todo-api
    ports:
      - "3000:3000"
    volumes:
      - .:backend/app
    environment:
      - NODE_ENV=development
    restart: always
  frontend:
    build: .
    container_name: todo-ui
    ports:
      - "5173:5173"
    volumes:
      - .:frontend/app
    environment:
      - NODE_ENV=development
    restart: always